In [1]:
import pandas as pd
import os

In [3]:
def filter_df(year: int, month: int, stocks):
    # read CSV and parse dates
    df = pd.read_csv(
        "filtered_df_stock_price_setsmart.csv", parse_dates=['date'])

    # filter by year and month
    filtered_df = df[(df['date'].dt.year == year) &
                     (df['date'].dt.month == month)]

    # filter only the required stock columns and the date column
    stock_px_last_cols = [stock for stock in stocks]
    stock_filter = filtered_df.columns.isin(
        stock_px_last_cols) | (filtered_df.columns == 'date')
    filtered_df = filtered_df.loc[:, stock_filter]

    return filtered_df


def port_value(year: int, month: int, stocks, money: int, number: int, detail):
    # filter for the specific year, month, stocks
    df = filter_df(year, month, stocks)
    initial_investment = money / number

    for col in df.columns:
        if col != 'date': 
            # the initial price for the stock
            initial_price = df[col].iloc[0]

            # column name for the portfolio value
            port_value_col = f"{col}_PORT VALUE"

            # แalculate portfolio value
            df[port_value_col] = (
                ((df[col] - initial_price) / initial_price) * initial_investment) + initial_investment

    # calculate total portfolio value by summing up only the portfolio value columns
    port_value_columns = [f"{col}_PORT VALUE" for col in stocks]
    df['total value'] = df[port_value_columns].sum(axis=1)

    # the result 
    port_value_df = df[['date'] + port_value_columns + ['total value']]

    #  final portfolio value at the end of the last row
    port_end_value = port_value_df['total value'].iloc[-1]

    # Save to file 
    filename = f"port_value_{year}_{month}_{detail}.csv"
    port_value_df.to_csv(filename, index=False)
    print(f"Data saved to {filename}")

    return port_value_df, port_end_value

# Portvalue (Example)

- Using news 10/2023 - 10/2024
- To predict 11/2023 - 11/2024

## 10/2023 -> 11/2023

In [19]:
port_value(2023, 11, ['DELTA', 'TIDLOR', 'CBG',
           'PTTEP', 'WHA'], 100, 5, 'high_risk_1')

Data saved to port_value_2023_11_high_risk_1.csv

(         date  DELTA_PORT VALUE  TIDLOR_PORT VALUE  CBG_PORT VALUE  \
 41 2023-11-01         20.000000          20.000000       20.000000
 42 2023-11-02         20.931677          21.450777       20.141343
 43 2023-11-03         20.745342          22.072539       20.424028
 44 2023-11-06         20.931677          21.865285       21.060071
 45 2023-11-07         20.931677          21.968912       20.706714
 46 2023-11-08         20.683230          22.383420       21.272085
 47 2023-11-09         20.745342          22.383420       21.272085
 48 2023-11-10         19.316770          21.968912       21.272085
 49 2023-11-13         19.689441          21.865285       21.413428
 50 2023-11-14         19.503106          22.279793       20.070671
 51 2023-11-15         20.931677          23.730570       21.130742
 52 2023-11-16         20.621118          23.316062       21.484099
 53 2023-11-17         20.186335          23.730570       22.614841
 54 2023-11-20         20.496894          23.523316       22.614841
 55 2023-11-21         20.869565          23.834197       22.544170
 56 2023-11-22         20.124224          23.316062       22.544170
 57 2023-11-23         19.937888          23.730570       22.473498
 58 2023-11-24         19.937888          23.316062       22.614841
 59 2023-11-27         19.875776          23.419689       22.473498
 60 2023-11-28         20.310559          23.834197       22.968198
 61 2023-11-29         19.130435          24.145078       23.321555
 62 2023-11-30         19.316770          23.730570       23.109541

     PTTEP_PORT VALUE  WHA_PORT VALUE  total value
 41         20.000000       20.000000   100.000000
 42         19.815951       20.325203   102.664951
 43         20.245399       20.325203   103.812511
 44         20.061350       20.934959   104.853342
 45         20.000000       21.138211   104.745514
 46         19.693252       20.528455   104.560441
 47         19.877301       20.934959   105.213106
 48         19.815951       19.430894   101.804612
 49         19.631902       19.268293   101.868348
 50         19.877301       19.593496   101.324366
 51         19.877301       20.731707   106.401997
 52         19.815951       20.528455   105.765685
 53         19.447853       20.325203   106.304802
 54         19.631902       20.528455   106.795409
 55         19.754601       20.325203   107.327736
 56         19.693252       20.081301   105.759008
 57         19.631902       20.243902   106.017761
 58         19.509202       20.243902   105.621896
 59         19.079755       20.162602   105.011320
 60         18.834356       20.243902   106.191212
 61         18.773006       19.918699   105.288773
 62         18.588957       20.325203   105.071041  ,
 105.07104107781157)

In [20]:
port_value(2023, 11, ['DELTA', 'TIDLOR', 'SNNP',
           'PTTEP', 'WHA'], 100, 5, 'high_risk_2')

Data saved to port_value_2023_11_high_risk_2.csv

(         date  DELTA_PORT VALUE  TIDLOR_PORT VALUE  SNNP_PORT VALUE  \
 41 2023-11-01         20.000000          20.000000        20.000000
 42 2023-11-02         20.931677          21.450777        21.139241
 43 2023-11-03         20.745342          22.072539        21.392405
 44 2023-11-06         20.931677          21.865285        20.506329
 45 2023-11-07         20.931677          21.968912        20.379747
 46 2023-11-08         20.683230          22.383420        21.012658
 47 2023-11-09         20.745342          22.383420        20.759494
 48 2023-11-10         19.316770          21.968912        20.253165
 49 2023-11-13         19.689441          21.865285        20.253165
 50 2023-11-14         19.503106          22.279793        20.253165
 51 2023-11-15         20.931677          23.730570        21.392405
 52 2023-11-16         20.621118          23.316062        21.392405
 53 2023-11-17         20.186335          23.730570        21.645570
 54 2023-11-20         20.496894          23.523316        21.518987
 55 2023-11-21         20.869565          23.834197        22.278481
 56 2023-11-22         20.124224          23.316062        21.898734
 57 2023-11-23         19.937888          23.730570        21.898734
 58 2023-11-24         19.937888          23.316062        21.392405
 59 2023-11-27         19.875776          23.419689        21.772152
 60 2023-11-28         20.310559          23.834197        21.012658
 61 2023-11-29         19.130435          24.145078        20.759494
 62 2023-11-30         19.316770          23.730570        20.759494

     PTTEP_PORT VALUE  WHA_PORT VALUE  total value
 41         20.000000       20.000000   100.000000
 42         19.815951       20.325203   103.662849
 43         20.245399       20.325203   104.780888
 44         20.061350       20.934959   104.299600
 45         20.000000       21.138211   104.418547
 46         19.693252       20.528455   104.301015
 47         19.877301       20.934959   104.700515
 48         19.815951       19.430894   100.785692
 49         19.631902       19.268293   100.708085
 50         19.877301       19.593496   101.506859
 51         19.877301       20.731707   106.663660
 52         19.815951       20.528455   105.673991
 53         19.447853       20.325203   105.335531
 54         19.631902       20.528455   105.699555
 55         19.754601       20.325203   107.062048
 56         19.693252       20.081301   105.113572
 57         19.631902       20.243902   105.442997
 58         19.509202       20.243902   104.399460
 59         19.079755       20.162602   104.309974
 60         18.834356       20.243902   104.235672
 61         18.773006       19.918699   102.726711
 62         18.588957       20.325203   102.720994  ,
 102.72099411265525)

In [21]:
port_value(2023, 11, ['DELTA', 'TIDLOR', 'KBANK', 'MINT', 'AOT'
                      ], 100, 5, 'high_risk_3')

Data saved to port_value_2023_11_high_risk_3.csv

(         date  DELTA_PORT VALUE  TIDLOR_PORT VALUE  KBANK_PORT VALUE  \
 41 2023-11-01         20.000000          20.000000         20.000000
 42 2023-11-02         20.931677          21.450777         20.000000
 43 2023-11-03         20.745342          22.072539         20.150943
 44 2023-11-06         20.931677          21.865285         19.924528
 45 2023-11-07         20.931677          21.968912         19.849057
 46 2023-11-08         20.683230          22.383420         20.075472
 47 2023-11-09         20.745342          22.383420         19.849057
 48 2023-11-10         19.316770          21.968912         19.849057
 49 2023-11-13         19.689441          21.865285         19.849057
 50 2023-11-14         19.503106          22.279793         19.924528
 51 2023-11-15         20.931677          23.730570         19.924528
 52 2023-11-16         20.621118          23.316062         19.924528
 53 2023-11-17         20.186335          23.730570         20.075472
 54 2023-11-20         20.496894          23.523316         19.773585
 55 2023-11-21         20.869565          23.834197         19.849057
 56 2023-11-22         20.124224          23.316062         19.924528
 57 2023-11-23         19.937888          23.730570         19.924528
 58 2023-11-24         19.937888          23.316062         19.924528
 59 2023-11-27         19.875776          23.419689         20.000000
 60 2023-11-28         20.310559          23.834197         20.075472
 61 2023-11-29         19.130435          24.145078         19.849057
 62 2023-11-30         19.316770          23.730570         19.320755

     MINT_PORT VALUE  AOT_PORT VALUE  total value
 41        20.000000       20.000000   100.000000
 42        20.540541       20.524345   103.447339
 43        21.081081       20.599251   104.649156
 44        20.900901       20.524345   104.146736
 45        20.360360       20.524345   103.634350
 46        20.540541       20.599251   104.281913
 47        20.000000       20.674157   103.651975
 48        20.000000       20.224719   101.359458
 49        19.639640       20.299625   101.343048
 50        19.459459       20.449438   101.616324
 51        20.180180       20.524345   105.291300
 52        19.639640       20.599251   104.100599
 53        19.819820       20.674157   104.486354
 54        20.180180       20.674157   104.648133
 55        20.180180       20.149813   104.882812
 56        20.180180       19.775281   103.320275
 57        20.180180       18.651685   102.424852
 58        20.000000       18.726592   101.905070
 59        19.819820       18.277154   101.392439
 60        19.639640       18.127341   101.987208
 61        19.459459       17.677903   100.261931
 62        19.639640       17.827715    99.835450  ,
 99.83544984694794)

In [22]:
port_value(2023, 11, ['DELTA', 'TIDLOR', 'SNNP',
           'PTTEP', 'WHA'], 100, 5, 'high_risk_4')

Data saved to port_value_2023_11_high_risk_4.csv

(         date  DELTA_PORT VALUE  TIDLOR_PORT VALUE  SNNP_PORT VALUE  \
 41 2023-11-01         20.000000          20.000000        20.000000
 42 2023-11-02         20.931677          21.450777        21.139241
 43 2023-11-03         20.745342          22.072539        21.392405
 44 2023-11-06         20.931677          21.865285        20.506329
 45 2023-11-07         20.931677          21.968912        20.379747
 46 2023-11-08         20.683230          22.383420        21.012658
 47 2023-11-09         20.745342          22.383420        20.759494
 48 2023-11-10         19.316770          21.968912        20.253165
 49 2023-11-13         19.689441          21.865285        20.253165
 50 2023-11-14         19.503106          22.279793        20.253165
 51 2023-11-15         20.931677          23.730570        21.392405
 52 2023-11-16         20.621118          23.316062        21.392405
 53 2023-11-17         20.186335          23.730570        21.645570
 54 2023-11-20         20.496894          23.523316        21.518987
 55 2023-11-21         20.869565          23.834197        22.278481
 56 2023-11-22         20.124224          23.316062        21.898734
 57 2023-11-23         19.937888          23.730570        21.898734
 58 2023-11-24         19.937888          23.316062        21.392405
 59 2023-11-27         19.875776          23.419689        21.772152
 60 2023-11-28         20.310559          23.834197        21.012658
 61 2023-11-29         19.130435          24.145078        20.759494
 62 2023-11-30         19.316770          23.730570        20.759494

     PTTEP_PORT VALUE  WHA_PORT VALUE  total value
 41         20.000000       20.000000   100.000000
 42         19.815951       20.325203   103.662849
 43         20.245399       20.325203   104.780888
 44         20.061350       20.934959   104.299600
 45         20.000000       21.138211   104.418547
 46         19.693252       20.528455   104.301015
 47         19.877301       20.934959   104.700515
 48         19.815951       19.430894   100.785692
 49         19.631902       19.268293   100.708085
 50         19.877301       19.593496   101.506859
 51         19.877301       20.731707   106.663660
 52         19.815951       20.528455   105.673991
 53         19.447853       20.325203   105.335531
 54         19.631902       20.528455   105.699555
 55         19.754601       20.325203   107.062048
 56         19.693252       20.081301   105.113572
 57         19.631902       20.243902   105.442997
 58         19.509202       20.243902   104.399460
 59         19.079755       20.162602   104.309974
 60         18.834356       20.243902   104.235672
 61         18.773006       19.918699   102.726711
 62         18.588957       20.325203   102.720994  ,
 102.72099411265525)

In [23]:
port_value(2023, 11, ['DELTA', 'TIDLOR', 'SNNP',
           'KBANK', 'AOT'], 100, 5, 'high_risk_5')

Data saved to port_value_2023_11_high_risk_5.csv

(         date  DELTA_PORT VALUE  TIDLOR_PORT VALUE  SNNP_PORT VALUE  \
 41 2023-11-01         20.000000          20.000000        20.000000
 42 2023-11-02         20.931677          21.450777        21.139241
 43 2023-11-03         20.745342          22.072539        21.392405
 44 2023-11-06         20.931677          21.865285        20.506329
 45 2023-11-07         20.931677          21.968912        20.379747
 46 2023-11-08         20.683230          22.383420        21.012658
 47 2023-11-09         20.745342          22.383420        20.759494
 48 2023-11-10         19.316770          21.968912        20.253165
 49 2023-11-13         19.689441          21.865285        20.253165
 50 2023-11-14         19.503106          22.279793        20.253165
 51 2023-11-15         20.931677          23.730570        21.392405
 52 2023-11-16         20.621118          23.316062        21.392405
 53 2023-11-17         20.186335          23.730570        21.645570
 54 2023-11-20         20.496894          23.523316        21.518987
 55 2023-11-21         20.869565          23.834197        22.278481
 56 2023-11-22         20.124224          23.316062        21.898734
 57 2023-11-23         19.937888          23.730570        21.898734
 58 2023-11-24         19.937888          23.316062        21.392405
 59 2023-11-27         19.875776          23.419689        21.772152
 60 2023-11-28         20.310559          23.834197        21.012658
 61 2023-11-29         19.130435          24.145078        20.759494
 62 2023-11-30         19.316770          23.730570        20.759494

     KBANK_PORT VALUE  AOT_PORT VALUE  total value
 41         20.000000       20.000000   100.000000
 42         20.000000       20.524345   104.046039
 43         20.150943       20.599251   104.960480
 44         19.924528       20.524345   103.752164
 45         19.849057       20.524345   103.653737
 46         20.075472       20.599251   104.754030
 47         19.849057       20.674157   104.411469
 48         19.849057       20.224719   101.612622
 49         19.849057       20.299625   101.956573
 50         19.924528       20.449438   102.410029
 51         19.924528       20.524345   106.503525
 52         19.924528       20.599251   105.853364
 53         20.075472       20.674157   106.312104
 54         19.773585       20.674157   105.986940
 55         19.849057       20.149813   106.981112
 56         19.924528       19.775281   105.038829
 57         19.924528       18.651685   104.143406
 58         19.924528       18.726592   103.297476
 59         20.000000       18.277154   103.344771
 60         20.075472       18.127341   103.360227
 61         19.849057       17.677903   101.561965
 62         19.320755       17.827715   100.955304  ,
 100.95530387819437)

In [24]:
port_value(2023, 11, ['DELTA', 'TIDLOR', 'SNNP',
           'PTTEP', 'WHA'], 100, 5, 'high_risk_6')

Data saved to port_value_2023_11_high_risk_6.csv

(         date  DELTA_PORT VALUE  TIDLOR_PORT VALUE  SNNP_PORT VALUE  \
 41 2023-11-01         20.000000          20.000000        20.000000
 42 2023-11-02         20.931677          21.450777        21.139241
 43 2023-11-03         20.745342          22.072539        21.392405
 44 2023-11-06         20.931677          21.865285        20.506329
 45 2023-11-07         20.931677          21.968912        20.379747
 46 2023-11-08         20.683230          22.383420        21.012658
 47 2023-11-09         20.745342          22.383420        20.759494
 48 2023-11-10         19.316770          21.968912        20.253165
 49 2023-11-13         19.689441          21.865285        20.253165
 50 2023-11-14         19.503106          22.279793        20.253165
 51 2023-11-15         20.931677          23.730570        21.392405
 52 2023-11-16         20.621118          23.316062        21.392405
 53 2023-11-17         20.186335          23.730570        21.645570
 54 2023-11-20         20.496894          23.523316        21.518987
 55 2023-11-21         20.869565          23.834197        22.278481
 56 2023-11-22         20.124224          23.316062        21.898734
 57 2023-11-23         19.937888          23.730570        21.898734
 58 2023-11-24         19.937888          23.316062        21.392405
 59 2023-11-27         19.875776          23.419689        21.772152
 60 2023-11-28         20.310559          23.834197        21.012658
 61 2023-11-29         19.130435          24.145078        20.759494
 62 2023-11-30         19.316770          23.730570        20.759494

     PTTEP_PORT VALUE  WHA_PORT VALUE  total value
 41         20.000000       20.000000   100.000000
 42         19.815951       20.325203   103.662849
 43         20.245399       20.325203   104.780888
 44         20.061350       20.934959   104.299600
 45         20.000000       21.138211   104.418547
 46         19.693252       20.528455   104.301015
 47         19.877301       20.934959   104.700515
 48         19.815951       19.430894   100.785692
 49         19.631902       19.268293   100.708085
 50         19.877301       19.593496   101.506859
 51         19.877301       20.731707   106.663660
 52         19.815951       20.528455   105.673991
 53         19.447853       20.325203   105.335531
 54         19.631902       20.528455   105.699555
 55         19.754601       20.325203   107.062048
 56         19.693252       20.081301   105.113572
 57         19.631902       20.243902   105.442997
 58         19.509202       20.243902   104.399460
 59         19.079755       20.162602   104.309974
 60         18.834356       20.243902   104.235672
 61         18.773006       19.918699   102.726711
 62         18.588957       20.325203   102.720994  ,
 102.72099411265525)

In [25]:
port_value(2023, 11, ['DELTA', 'TIDLOR', 'SNNP',
           'KBANK', 'AOT'], 100, 5, 'high_risk_7')

Data saved to port_value_2023_11_high_risk_7.csv

(         date  DELTA_PORT VALUE  TIDLOR_PORT VALUE  SNNP_PORT VALUE  \
 41 2023-11-01         20.000000          20.000000        20.000000
 42 2023-11-02         20.931677          21.450777        21.139241
 43 2023-11-03         20.745342          22.072539        21.392405
 44 2023-11-06         20.931677          21.865285        20.506329
 45 2023-11-07         20.931677          21.968912        20.379747
 46 2023-11-08         20.683230          22.383420        21.012658
 47 2023-11-09         20.745342          22.383420        20.759494
 48 2023-11-10         19.316770          21.968912        20.253165
 49 2023-11-13         19.689441          21.865285        20.253165
 50 2023-11-14         19.503106          22.279793        20.253165
 51 2023-11-15         20.931677          23.730570        21.392405
 52 2023-11-16         20.621118          23.316062        21.392405
 53 2023-11-17         20.186335          23.730570        21.645570
 54 2023-11-20         20.496894          23.523316        21.518987
 55 2023-11-21         20.869565          23.834197        22.278481
 56 2023-11-22         20.124224          23.316062        21.898734
 57 2023-11-23         19.937888          23.730570        21.898734
 58 2023-11-24         19.937888          23.316062        21.392405
 59 2023-11-27         19.875776          23.419689        21.772152
 60 2023-11-28         20.310559          23.834197        21.012658
 61 2023-11-29         19.130435          24.145078        20.759494
 62 2023-11-30         19.316770          23.730570        20.759494

     KBANK_PORT VALUE  AOT_PORT VALUE  total value
 41         20.000000       20.000000   100.000000
 42         20.000000       20.524345   104.046039
 43         20.150943       20.599251   104.960480
 44         19.924528       20.524345   103.752164
 45         19.849057       20.524345   103.653737
 46         20.075472       20.599251   104.754030
 47         19.849057       20.674157   104.411469
 48         19.849057       20.224719   101.612622
 49         19.849057       20.299625   101.956573
 50         19.924528       20.449438   102.410029
 51         19.924528       20.524345   106.503525
 52         19.924528       20.599251   105.853364
 53         20.075472       20.674157   106.312104
 54         19.773585       20.674157   105.986940
 55         19.849057       20.149813   106.981112
 56         19.924528       19.775281   105.038829
 57         19.924528       18.651685   104.143406
 58         19.924528       18.726592   103.297476
 59         20.000000       18.277154   103.344771
 60         20.075472       18.127341   103.360227
 61         19.849057       17.677903   101.561965
 62         19.320755       17.827715   100.955304  ,
 100.95530387819437)

In [26]:
port_value(2023, 11, ['TIDLOR', 'PTTEP', 'WHA',
           'MINT', 'KBANK'], 100, 5, 'high_risk_8')

Data saved to port_value_2023_11_high_risk_8.csv

(         date  TIDLOR_PORT VALUE  PTTEP_PORT VALUE  WHA_PORT VALUE  \
 41 2023-11-01          20.000000         20.000000       20.000000
 42 2023-11-02          21.450777         19.815951       20.325203
 43 2023-11-03          22.072539         20.245399       20.325203
 44 2023-11-06          21.865285         20.061350       20.934959
 45 2023-11-07          21.968912         20.000000       21.138211
 46 2023-11-08          22.383420         19.693252       20.528455
 47 2023-11-09          22.383420         19.877301       20.934959
 48 2023-11-10          21.968912         19.815951       19.430894
 49 2023-11-13          21.865285         19.631902       19.268293
 50 2023-11-14          22.279793         19.877301       19.593496
 51 2023-11-15          23.730570         19.877301       20.731707
 52 2023-11-16          23.316062         19.815951       20.528455
 53 2023-11-17          23.730570         19.447853       20.325203
 54 2023-11-20          23.523316         19.631902       20.528455
 55 2023-11-21          23.834197         19.754601       20.325203
 56 2023-11-22          23.316062         19.693252       20.081301
 57 2023-11-23          23.730570         19.631902       20.243902
 58 2023-11-24          23.316062         19.509202       20.243902
 59 2023-11-27          23.419689         19.079755       20.162602
 60 2023-11-28          23.834197         18.834356       20.243902
 61 2023-11-29          24.145078         18.773006       19.918699
 62 2023-11-30          23.730570         18.588957       20.325203

     MINT_PORT VALUE  KBANK_PORT VALUE  total value
 41        20.000000         20.000000   100.000000
 42        20.540541         20.000000   102.132472
 43        21.081081         20.150943   103.875165
 44        20.900901         19.924528   103.687023
 45        20.360360         19.849057   103.316540
 46        20.540541         20.075472   103.221139
 47        20.000000         19.849057   103.044736
 48        20.000000         19.849057   101.064814
 49        19.639640         19.849057   100.254176
 50        19.459459         19.924528   101.134577
 51        20.180180         19.924528   104.444286
 52        19.639640         19.924528   103.224636
 53        19.819820         20.075472   103.398917
 54        20.180180         19.773585   103.637438
 55        20.180180         19.849057   103.943238
 56        20.180180         19.924528   103.195323
 57        20.180180         19.924528   103.711083
 58        20.000000         19.924528   102.993695
 59        19.819820         20.000000   102.481865
 60        19.639640         20.075472   102.627566
 61        19.459459         19.849057   102.145299
 62        19.639640         19.320755   101.605125  ,
 101.60512461205454)

In [27]:
port_value(2023, 11, ['DELTA', 'TIDLOR', 'SNNP',
           'KBANK', 'AOT'], 100, 5, 'high_risk_9')

Data saved to port_value_2023_11_high_risk_9.csv

(         date  DELTA_PORT VALUE  TIDLOR_PORT VALUE  SNNP_PORT VALUE  \
 41 2023-11-01         20.000000          20.000000        20.000000
 42 2023-11-02         20.931677          21.450777        21.139241
 43 2023-11-03         20.745342          22.072539        21.392405
 44 2023-11-06         20.931677          21.865285        20.506329
 45 2023-11-07         20.931677          21.968912        20.379747
 46 2023-11-08         20.683230          22.383420        21.012658
 47 2023-11-09         20.745342          22.383420        20.759494
 48 2023-11-10         19.316770          21.968912        20.253165
 49 2023-11-13         19.689441          21.865285        20.253165
 50 2023-11-14         19.503106          22.279793        20.253165
 51 2023-11-15         20.931677          23.730570        21.392405
 52 2023-11-16         20.621118          23.316062        21.392405
 53 2023-11-17         20.186335          23.730570        21.645570
 54 2023-11-20         20.496894          23.523316        21.518987
 55 2023-11-21         20.869565          23.834197        22.278481
 56 2023-11-22         20.124224          23.316062        21.898734
 57 2023-11-23         19.937888          23.730570        21.898734
 58 2023-11-24         19.937888          23.316062        21.392405
 59 2023-11-27         19.875776          23.419689        21.772152
 60 2023-11-28         20.310559          23.834197        21.012658
 61 2023-11-29         19.130435          24.145078        20.759494
 62 2023-11-30         19.316770          23.730570        20.759494

     KBANK_PORT VALUE  AOT_PORT VALUE  total value
 41         20.000000       20.000000   100.000000
 42         20.000000       20.524345   104.046039
 43         20.150943       20.599251   104.960480
 44         19.924528       20.524345   103.752164
 45         19.849057       20.524345   103.653737
 46         20.075472       20.599251   104.754030
 47         19.849057       20.674157   104.411469
 48         19.849057       20.224719   101.612622
 49         19.849057       20.299625   101.956573
 50         19.924528       20.449438   102.410029
 51         19.924528       20.524345   106.503525
 52         19.924528       20.599251   105.853364
 53         20.075472       20.674157   106.312104
 54         19.773585       20.674157   105.986940
 55         19.849057       20.149813   106.981112
 56         19.924528       19.775281   105.038829
 57         19.924528       18.651685   104.143406
 58         19.924528       18.726592   103.297476
 59         20.000000       18.277154   103.344771
 60         20.075472       18.127341   103.360227
 61         19.849057       17.677903   101.561965
 62         19.320755       17.827715   100.955304  ,
 100.95530387819437)

In [28]:
port_value(2023, 11, ['DELTA', 'TIDLOR', 'SNNP',
           'PTTEP', 'WHA'], 100, 5, 'high_risk_0')

Data saved to port_value_2023_11_high_risk_0.csv

(         date  DELTA_PORT VALUE  TIDLOR_PORT VALUE  SNNP_PORT VALUE  \
 41 2023-11-01         20.000000          20.000000        20.000000
 42 2023-11-02         20.931677          21.450777        21.139241
 43 2023-11-03         20.745342          22.072539        21.392405
 44 2023-11-06         20.931677          21.865285        20.506329
 45 2023-11-07         20.931677          21.968912        20.379747
 46 2023-11-08         20.683230          22.383420        21.012658
 47 2023-11-09         20.745342          22.383420        20.759494
 48 2023-11-10         19.316770          21.968912        20.253165
 49 2023-11-13         19.689441          21.865285        20.253165
 50 2023-11-14         19.503106          22.279793        20.253165
 51 2023-11-15         20.931677          23.730570        21.392405
 52 2023-11-16         20.621118          23.316062        21.392405
 53 2023-11-17         20.186335          23.730570        21.645570
 54 2023-11-20         20.496894          23.523316        21.518987
 55 2023-11-21         20.869565          23.834197        22.278481
 56 2023-11-22         20.124224          23.316062        21.898734
 57 2023-11-23         19.937888          23.730570        21.898734
 58 2023-11-24         19.937888          23.316062        21.392405
 59 2023-11-27         19.875776          23.419689        21.772152
 60 2023-11-28         20.310559          23.834197        21.012658
 61 2023-11-29         19.130435          24.145078        20.759494
 62 2023-11-30         19.316770          23.730570        20.759494

     PTTEP_PORT VALUE  WHA_PORT VALUE  total value
 41         20.000000       20.000000   100.000000
 42         19.815951       20.325203   103.662849
 43         20.245399       20.325203   104.780888
 44         20.061350       20.934959   104.299600
 45         20.000000       21.138211   104.418547
 46         19.693252       20.528455   104.301015
 47         19.877301       20.934959   104.700515
 48         19.815951       19.430894   100.785692
 49         19.631902       19.268293   100.708085
 50         19.877301       19.593496   101.506859
 51         19.877301       20.731707   106.663660
 52         19.815951       20.528455   105.673991
 53         19.447853       20.325203   105.335531
 54         19.631902       20.528455   105.699555
 55         19.754601       20.325203   107.062048
 56         19.693252       20.081301   105.113572
 57         19.631902       20.243902   105.442997
 58         19.509202       20.243902   104.399460
 59         19.079755       20.162602   104.309974
 60         18.834356       20.243902   104.235672
 61         18.773006       19.918699   102.726711
 62         18.588957       20.325203   102.720994  ,
 102.72099411265525)

In [30]:
import pandas as pd
import os


def concatenate_total_values(folder_path):
    dfs = []
    file_number = 1

    # Iterate over files in the folder
    for file_name in os.listdir(folder_path):
        if file_name.endswith('.csv'):
            file_path = os.path.join(folder_path, file_name)
            
            df = pd.read_csv(file_path)
            # Rename the total value column to total value from {file_number}
            df.rename(
                columns={'total value': f'total value from {file_number}'}, inplace=True)
            # Extract only 'DATES' and the renamed total value column
            df_filtered = df[['date', f'total value from {file_number}']]
            dfs.append(df_filtered)
            file_number += 1

    # merge 
    concatenated_df = dfs[0]
    for df in dfs[1:]:
        concatenated_df = pd.merge(
            concatenated_df, df, on='date', how='outer')

    # port average  
    total_value_columns = [
        col for col in concatenated_df.columns if col.startswith('total value from')]
    concatenated_df['average total value'] = concatenated_df[total_value_columns].mean(
        axis=1)

    last_average_total_value = concatenated_df['average total value'].iloc[-1]
    return concatenated_df, last_average_total_value


folder_path = "C:\\stuff\\SR\\python_my_code\\using code\\using\\final\\port_balance_final_excel\\11_2023_high_risk"
combined_df, last_average_total_value = concatenate_total_values(folder_path)

print(combined_df)
print(last_average_total_value)
combined_df.to_csv(
    'avg_all10port_11_2023_highrisk.csv', index=False)

          date  total value from 1  total value from 2  total value from 3  \
0   2023-11-01          100.000000          100.000000          100.000000
1   2023-11-02          103.662849          102.664951          103.662849
2   2023-11-03          104.780888          103.812511          104.780888
3   2023-11-06          104.299600          104.853342          104.299600
4   2023-11-07          104.418547          104.745514          104.418547
5   2023-11-08          104.301015          104.560441          104.301015
6   2023-11-09          104.700515          105.213106          104.700515
7   2023-11-10          100.785692          101.804612          100.785692
8   2023-11-13          100.708085          101.868348          100.708085
9   2023-11-14          101.506859          101.324366          101.506859
10  2023-11-15          106.663660          106.401997          106.663660
11  2023-11-16          105.673991          105.765685          105.673991
12  2023-11-17          105.335531          106.304802          105.335531
13  2023-11-20          105.699555          106.795409          105.699555
14  2023-11-21          107.062048          107.327736          107.062048
15  2023-11-22          105.113572          105.759008          105.113572
16  2023-11-23          105.442997          106.017761          105.442997
17  2023-11-24          104.399460          105.621896          104.399460
18  2023-11-27          104.309974          105.011320          104.309974
19  2023-11-28          104.235672          106.191212          104.235672
20  2023-11-29          102.726711          105.288773          102.726711
21  2023-11-30          102.720994          105.071041          102.720994

    total value from 4  total value from 5  total value from 6  \
0           100.000000          100.000000          100.000000
1           103.447339          103.662849          104.046039
2           104.649156          104.780888          104.960480
3           104.146736          104.299600          103.752164
4           103.634350          104.418547          103.653737
5           104.281913          104.301015          104.754030
6           103.651975          104.700515          104.411469
7           101.359458          100.785692          101.612622
8           101.343048          100.708085          101.956573
9           101.616324          101.506859          102.410029
10          105.291300          106.663660          106.503525
11          104.100599          105.673991          105.853364
12          104.486354          105.335531          106.312104
13          104.648133          105.699555          105.986940
14          104.882812          107.062048          106.981112
15          103.320275          105.113572          105.038829
16          102.424852          105.442997          104.143406
17          101.905070          104.399460          103.297476
18          101.392439          104.309974          103.344771
19          101.987208          104.235672          103.360227
20          100.261931          102.726711          101.561965
21           99.835450          102.720994          100.955304

    total value from 7  total value from 8  total value from 9  \
0           100.000000          100.000000          100.000000
1           103.662849          104.046039          102.132472
2           104.780888          104.960480          103.875165
3           104.299600          103.752164          103.687023
4           104.418547          103.653737          103.316540
5           104.301015          104.754030          103.221139
6           104.700515          104.411469          103.044736
7           100.785692          101.612622          101.064814
8           100.708085          101.956573          100.254176
9           101.506859          102.410029          101.134577
10          106.663660          106.503525          104.444286
11          105.673991          105.853364          103.224636
12          105.335531          106.312104          103.398917
13          105.699555          105.986940          103.637438
14          107.062048          106.981112          103.943238
15          105.113572          105.038829          103.195323
16          105.442997          104.143406          103.711083
17          104.399460          103.297476          102.993695
18          104.309974          103.344771          102.481865
19          104.235672          103.360227          102.627566
20          102.726711          101.561965          102.145299
21          102.720994          100.955304          101.605125

    total value from 10  average total value
0            100.000000           100.000000
1            104.046039           103.503428
2            104.960480           104.634182
3            103.752164           104.114199
4            103.653737           104.033180
5            104.754030           104.352964
6            104.411469           104.394628
7            101.612622           101.220952
8            101.956573           101.216763
9            102.410029           101.733279
10           106.503525           106.230280
11           105.853364           105.334698
12           106.312104           105.446851
13           105.986940           105.584002
14           106.981112           106.534531
15           105.038829           104.784538
16           104.143406           104.635590
17           103.297476           103.801093
18           103.344771           103.615983
19           103.360227           103.782936
20           101.561965           102.328875
21           100.955304           102.026150
102.02615036220182